# Site settings
title: hagridaaron
description: 'A place to document things I work on, am learning, and am interested in. My thoughts are my own.'
url: 'http://hagridaron.com'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Aaron Tracy'
  email: hagridaaron.services@gmail.com
  twitter_username: hagridaaron
  github_username:  hagridaron
  linkedin_username:  hagridaaron

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
remote_theme: joshgerdes/jekyll-uno
sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
